"""
Libraries: NumPy & Pandas - Assignment
Pwskills

Dataset: retail_dataset_.csv
(Place this file in the same directory as this script, or update the
CSV_PATH variable below with the correct path.)
"""

import pandas as pd
import numpy as np

CSV_PATH = "retail_dataset_.csv"

# ---------------------------------------------------------------------------
# Q1. Load the given retail sales dataset into a Pandas DataFrame and
# display the first 5 rows along with the dataset information to
# understand its structure.
# ---------------------------------------------------------------------------
df = pd.read_csv(CSV_PATH)

print("Q1: First 5 rows")
print(df.head())

print("\nQ1: Dataset Info")
print(df.info())


# ---------------------------------------------------------------------------
# Q2. Inspect the dataset and identify missing values in each column.
# Display the total number of missing values present in the dataset.
# ---------------------------------------------------------------------------
print("\nQ2: Missing values per column")
print(df.isnull().sum())

print("\nQ2: Total missing values in the dataset:", df.isnull().sum().sum())


# ---------------------------------------------------------------------------
# Q3. Replace missing values in the Quantity and Price columns with their
# respective mean values using Pandas.
# ---------------------------------------------------------------------------
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

print("\nQ3: Missing values after filling Quantity & Price with mean")
print(df.isnull().sum())


# ---------------------------------------------------------------------------
# Q4. Remove all rows where the Product Category or Region column
# contains missing values.
# ---------------------------------------------------------------------------
df = df.dropna(subset=['Product Category', 'Region'])

print("\nQ4: Dataset shape after dropping rows with missing "
      "Product Category / Region:", df.shape)


# ---------------------------------------------------------------------------
# Q5. Create a new column called Revenue using NumPy, where:
# Revenue = Quantity x Price
# Display the updated dataset with the new column.
# ---------------------------------------------------------------------------
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

print("\nQ5: Updated dataset with Revenue column")
print(df.head())


# ---------------------------------------------------------------------------
# Q6. Using NumPy, calculate the total revenue generated from all
# transactions in the dataset.
# ---------------------------------------------------------------------------
total_revenue = np.sum(df['Revenue'])
print("\nQ6: Total revenue generated from all transactions:", total_revenue)


# ---------------------------------------------------------------------------
# Q7. Group the dataset by Product Category and calculate the total
# revenue generated by each category.
# ---------------------------------------------------------------------------
category_revenue = df.groupby('Product Category')['Revenue'].sum()

print("\nQ7: Total revenue by Product Category")
print(category_revenue)


# ---------------------------------------------------------------------------
# Q8. Based on the revenue calculated for each product category,
# identify the top 3 categories with the highest revenue and the
# bottom 3 categories with the lowest revenue.
# ---------------------------------------------------------------------------
sorted_category_revenue = category_revenue.sort_values(ascending=False)

print("\nQ8: Top 3 categories by revenue")
print(sorted_category_revenue.head(3))

print("\nQ8: Bottom 3 categories by revenue")
print(sorted_category_revenue.tail(3))


# ---------------------------------------------------------------------------
# Q9. Group the dataset by Region and calculate the total revenue
# generated in each region. Identify the region with the highest
# revenue and the region with the lowest revenue.
# ---------------------------------------------------------------------------
region_revenue = df.groupby('Region')['Revenue'].sum()

print("\nQ9: Total revenue by Region")
print(region_revenue)
print("Q9: Region with highest revenue:",
      region_revenue.idxmax(), "->", region_revenue.max())
print("Q9: Region with lowest revenue:",
      region_revenue.idxmin(), "->", region_revenue.min())


# ---------------------------------------------------------------------------
# Q10. Extract the month from the Date column using Pandas and group
# the dataset by month to calculate the total monthly revenue.
# Also, calculate the mean, median, and standard deviation of the
# Revenue column using NumPy.
# ---------------------------------------------------------------------------
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Month'] = df['Date'].dt.month

monthly_revenue = df.groupby('Month')['Revenue'].sum()
print("\nQ10: Total monthly revenue")
print(monthly_revenue)

mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])

print("\nQ10: Revenue statistics")
print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation of Revenue:", std_revenue)
